_BASE_: "../oicr_WSR_18_DC5_1x.yaml"
WSL:
  REFINE_NUM: 4
  REFINE_REG: [True, True, True, True]
  SAMPLING:
    SAMPLING_ON: True
    #IOU_THRESHOLDS: [[0.2, 0.8], [0.3, 0.7], [0.4, 0.6], [0.5]]
    #IOU_LABELS: [[0, -1, 1], [0, -1, 1], [0, -1, 1], [0, 1]]
    IOU_THRESHOLDS: [[0.3], [0.4], [0.5], [0.6]]
    IOU_LABELS: [[0, 1], [0, 1], [0, 1], [0, 1]]
