_BASE_: "../oicr_WSR_18_DC5_1x.yaml"
WSL:
  REFINE_NUM: 4
  REFINE_REG: [True, True, True, True]
  CASCADE_ON: True
MODEL:
  ROI_HEADS:
    NAME: "CascadeOICRROIHeads"
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
TEST:
  EVAL_PERIOD: 10001
