_BASE_: "../Base-RCNN-DilatedC5.yaml"
DATASETS:
  TRAIN: ('voc_2007_train', 'voc_2007_val')
  PROPOSAL_FILES_TRAIN: ('datasets/proposals/mcg_voc_2007_train_d2.pkl', 'datasets/proposals/mcg_voc_2007_val_d2.pkl')
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 4000
  TEST: ('voc_2007_test',)
  PROPOSAL_FILES_TEST: ('datasets/proposals/mcg_voc_2007_test_d2.pkl', )
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 4000
