_BASE_: "../../../../configs/Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "models/DRN-WSOD/resnet50_ws_model_120_d2.pkl"
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  MASK_ON: False
  BACKBONE:
    NAME: "build_wsl_resnet_backbone"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
    NAME: "WSRes5ROIHeads"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_train', 'voc_2007_val')
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 200
  REFERENCE_WORLD_SIZE: 8
TEST:
  EVAL_PERIOD: 5000
