_BASE_: "../../../../configs/Base-RCNN-DilatedC5.yaml"
MODEL:
  WEIGHTS: "models/DRN-WSOD/resnet18_ws_model_120_d2.pkl"
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  MASK_ON: False
  BACKBONE:
    NAME: "build_wsl_resnet_backbone"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: "DiscriminativeAdaptionNeck"
    NUM_CONV: 0
    NUM_FC: 2
    DAN_DIM: [4096, 4096]
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_train_pgt', 'voc_2007_val_pgt')
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 200
  REFERENCE_WORLD_SIZE: 8
TEST:
  EVAL_PERIOD: 5000
