_BASE_: "Base-RCNN-DilatedC5.yaml"
#_BASE_: "Base-RCNN-DilatedC5_VOC2012.yaml"
#_BASE_: "Base-RCNN-DilatedC5_VOC2012_Ins.yaml"
MODEL:
  WEIGHTS: "models/VGG/VGG_ILSVRC_16_layers_v1_d2.pkl"
  PIXEL_MEAN: [103.939, 116.779, 123.68]
  MASK_ON: False
  LOAD_PROPOSALS: True
  BACKBONE:
    NAME: "build_vgg_backbone"
    FREEZE_AT: 5
  VGG:
    DEPTH: 16
    CONV5_DILATION: 2
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
    MIN_SIZE: 20
  ROI_HEADS:
    NAME: "OICRROIHeads"
    IN_FEATURES: ["plain5"]
    NUM_CLASSES: 20
    SCORE_THRESH_TEST: 0.00001
    NMS_THRESH_TEST: 0.3
    #IOU_THRESHOLDS: [0.1, 0.5]
    #IOU_LABELS: [-1, 0, 1]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIPool"
    NUM_CONV: 0
    NUM_FC: 2
    DAN_DIM: [4096, 4096]
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 4000
  CROP:
    ENABLED: True
SOLVER:
  STEPS: (35000, 50000)
  MAX_ITER: 50000  # 40.0 epochs for 07
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
  EVAL_PERIOD: 10000
WSL:
  ITER_SIZE: 1
  MEAN_LOSS: True
