_BASE_: "uwsod_WSR_18_DC5_1x.yaml"
MODEL:
  RPN:
    PRE_NMS_TOPK_TRAIN: 10240
    PRE_NMS_TOPK_TEST: 10240
    NMS_THRESH: 0.8
WSL:
  REFINE_MIST: False
  SAMPLING:
    IOU_THRESHOLDS: [[0.3], [0.4], [0.5], [0.6]]
    BATCH_SIZE_PER_IMAGE: [512, 512, 512, 512]
    POSITIVE_FRACTION: [0.25, 0.25, 0.25, 0.25]
  CLS_AGNOSTIC_BBOX_KNOWN: True
