_BASE_: "Base-RCNN-DilatedC5.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  LOAD_PROPOSALS: True
  BACKBONE:
    NAME: "build_resnet_backbone"
    FREEZE_AT: 5
  RESNETS:
    DEPTH: 50
    RES5_DILATION: 1
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
    MIN_SIZE: 20
  ROI_HEADS:
    NUM_CLASSES: 20
    SCORE_THRESH_TEST: 0.000000001
    NMS_THRESH_TEST: 0.5
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIPool"
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 0
    NUM_FC: 2
    #CONV_DIM: 128
    FC_DIM: 1024
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 2000
  CROP:
    ENABLED: True
SOLVER:
  STEPS: (35000, 35000)
  MAX_ITER: 35000
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
  EVAL_PERIOD: 10000
#WSL:
  #ITER_SIZE: 32
  #MEAN_LOSS: False
